/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nelltictactoe;

import javax.swing.JOptionPane;

/**
 *
 * @author student1
 */
public class tictactoe extends javax.swing.JFrame {
    int count = 0;
    int Counts = 0;
    int x = 1;
    int d = 0;
    
    
    /**
     * Creates new form tictactoe
     */
    public tictactoe() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC TAC TOE");
        setResizable(false);

        btn1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn10.setText("RULES");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn11.setText("INFORMATION");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SCORE :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PLAYER X :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("PLAYER O :");

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl1.setText("0");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void checkWS(){
        lbl1.setText(String.valueOf(count));
        lbl2.setText(String.valueOf(Counts));
    }
        
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn3.setText("O");
            
        }else if(x % 2 == 1){
            btn3.setText("X");
           
        }
        x++;
        d++;
        checkWS();
        btn3.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
            
        
        
        if(btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                count = 0;
                Counts = 0;

            }
        }else if(btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl2.setText("0");
                lbl1.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn3.getText().equals("X") && btn5.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                count = 0;
                Counts = 0;

            }
        }else if(btn3.getText().equals("O") && btn5.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn3.getText().equals("X") && btn6.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                count = 0;
                Counts = 0;

            }
        }else if(btn3.getText().equals("O") && btn6.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                count = 0;
                Counts = 0;

            }
        }else if(btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if (!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!");
    
            resetGame();

        }   
           
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn1.setText("O");
            
        }else if(x % 2 == 1){
            btn1.setText("X");
           
        }
        x++;
        d++;
        checkWS();

        btn1.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
        if(btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                count = 0;
                Counts = 0;

            }
        }else if(btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn4.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("O") && btn4.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if (!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            resetGame();
        } 
           
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn2.setText("O");
            
        }else if(x % 2 == 1){
            btn2.setText("X");
           
        } 
        x++;
        d++;
        checkWS();

        btn2.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
        if(btn1.getText().equals("X") && btn2.getText().equals("X") && btn3.getText().equals("X")){
           JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("O") && btn2.getText().equals("O") && btn3.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
            
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn2.getText().equals("X") && btn5.getText().equals("X") && btn8.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn2.getText().equals("O") && btn5.getText().equals("O") && btn8.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            
            resetGame();
        }
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn4.setText("O");
            
        }else if(x % 2 == 1){
            btn4.setText("X");
           
        } 
        x++;
        d++;
        btn4.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
        if(btn4.getText().equals("X") && btn5.getText().equals("X") && btn6.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
            
           
        }else if(btn4.getText().equals("O") && btn5.getText().equals("O") && btn6.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn4.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("O") && btn4.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if (!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
            resetGame();
        } 
            
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn5.setText("O");
            
        }else if(x % 2 == 1){
            btn5.setText("X");
           
        } 
        x++;
        d++;
        btn5.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
        if(btn4.getText().equals("X") && btn5.getText().equals("X") && btn6.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn4.getText().equals("O") && btn5.getText().equals("O") && btn6.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
           
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (btn3.getText().equals("X") && btn5.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn3.getText().equals("O") && btn5.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn2.getText().equals("X") && btn5.getText().equals("X") && btn8.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn2.getText().equals("O") && btn5.getText().equals("O") && btn8.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
    
        resetGame();
        }
      
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn6.setText("O");
            
        }else if(x % 2 == 1){
            btn6.setText("X");
           
        } 
        x++;
        d++;
        btn6.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        
        if(btn4.getText().equals("X") && btn5.getText().equals("X") && btn6.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn4.getText().equals("O") && btn5.getText().equals("O") && btn6.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn3.getText().equals("X") && btn6.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn3.getText().equals("O") && btn6.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!");
    
            resetGame();
        }
         
        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn7.setText("O");
            
        }else if(x % 2 == 1){
            btn7.setText("X");
           
        } 
        x++;
        d++;
        btn7.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        if(btn7.getText().equals("X") && btn8.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if(btn7.getText().equals("O") && btn8.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (btn3.getText().equals("X") && btn5.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (btn3.getText().equals("O") && btn5.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++; 
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (btn1.getText().equals("X") && btn4.getText().equals("X") && btn7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (btn1.getText().equals("O") && btn4.getText().equals("O") && btn7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;
               
            }
        }else if (!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!");

            resetGame();
        }   
            
        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn8.setText("O");
            
        }else if(x % 2 == 1){
            btn8.setText("X");
           
        } 
        x++;
        d++;
        btn8.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        if(btn7.getText().equals("X") && btn8.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn7.getText().equals("O") && btn8.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn2.getText().equals("X") && btn5.getText().equals("X") && btn8.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn2.getText().equals("O") && btn5.getText().equals("O") && btn8.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!");
            resetGame();
        }    
            
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(x % 2 == 0){
            btn9.setText("O");
            
        }else if(x % 2 == 1){
            btn9.setText("X");
           
        } 
        x++;
        d++;
        btn9.setEnabled(false);
        btn10.setEnabled(false);
        btn11.setEnabled(false);
        if(btn7.getText().equals("X") && btn8.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn7.getText().equals("O") && btn8.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("X") && btn5.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn1.getText().equals("O") && btn5.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn3.getText().equals("X") && btn6.getText().equals("X") && btn9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "Player X", "Win", JOptionPane.INFORMATION_MESSAGE);
            count++;
            lbl1.setText(String.valueOf(count));
            x = 1;
          
            
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);

            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(count == 3){
                lbl1.setText("3");
                lbl2.setText(String.valueOf(Counts));
                JOptionPane.showMessageDialog(this, "Player X won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(btn3.getText().equals("O") && btn6.getText().equals("O") && btn9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "Player O", "Win", JOptionPane.INFORMATION_MESSAGE);
            Counts++;
            lbl2.setText(String.valueOf(Counts));
            x = 1;
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            btn10.setEnabled(true);
            btn11.setEnabled(true);
           
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            if(Counts == 3){
                lbl2.setText("3");
                lbl1.setText(String.valueOf(count));
                JOptionPane.showMessageDialog(this, "Player O won");
                lbl1.setText("0");
                lbl2.setText("0");
                Counts = 0;
                count = 0;

            }
        }else if(!btn1.getText().isEmpty() && !btn2.getText().isEmpty() && !btn3.getText().isEmpty() &&
            !btn4.getText().isEmpty() && !btn5.getText().isEmpty() && !btn6.getText().isEmpty() &&
            !btn7.getText().isEmpty() && !btn8.getText().isEmpty() && !btn9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Draw!");
    
            resetGame();
        }
      
    }//GEN-LAST:event_btn9ActionPerformed
    
    private void resetGame(){
        x = 1;
        
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn10.setEnabled(true);
        btn11.setEnabled(true);

        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
    
    }
    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Molejon, Ronell C.", "Informaton", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        JOptionPane.showMessageDialog(this, "The first to get 3 points is the winner", "Rules", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
